`default_nettype none
`timescale 1ns/1ps
// rtl/mlkem/mlkem_ctl_rom3.sv
// GENERATED by scripts/gen_mlkem_ctl_rom3.py from tb/golden/mlkem_ctl_model3.py. Do not hand-edit.
// Micro-instruction word [39:0]: opc[39:36] 0 END, 1 LDP, 2 STP, 3 HST, 4 HFD, 5 HGT, 6 SDL, 7 RUN, 8 WR32, 9 RD32, 10 CMP, 11 BGS, 12 JN, 13 RUNS, 14 RUNJ.
//   RUNS: engine program[35:34], mask[33:22] of the slots loaded behind the engine (bit s = slot s); starts the engine and continues   RUNJ: no field (waits until the engine is done).
//   BGS: job start word[35:30] (the job words HST, HFD..., HGT, END follow the main program END)   JN: no field (waits for the background hash job).
//   LDP / STP: slot[35:32] region[31:30] word offset[29:21] dsel[20:19] (0: d = 1, 1: 4, 2: 10, 3: 12)
//   HST: sel[35:34] (0 H, 1 G, 2 J) length in bytes[33:23]      HFD: source[35:33] (0 KB, 1 CB, 2 CB2, 3 RF, 4 constant word 0x03) word offset[32:24] words[23:15]
//   HGT: dstA[35:33] dstB[32:30] (register numbers)             RUN: engine program[35:34]      WR32 / RD32: register[35:33] KB word offset[32:24]
// Programs (op_i): 0 KeyGen, 1 Encaps, 2 Decaps. Straight-line main code ending with END, then the words of one background hash job (also straight-line, ending with END). Unlisted addresses return END.

module mlkem_ctl_rom3 (
    input  wire  [1:0]  op_i,
    input  wire  [5:0]  pc_i,
    output logic [39:0] word_o
);

  always_comb begin
    case ({op_i, pc_i})
      {2'd0, 6'd0}: word_o = 40'h3410800000;   // keygen 0: HST 1 33
      {2'd0, 6'd1}: word_o = 40'h4600020000;   // keygen 1: HFD 3 0 4
      {2'd0, 6'd2}: word_o = 40'h4800008000;   // keygen 2: HFD 4 0 1
      {2'd0, 6'd3}: word_o = 40'h5700000000;   // keygen 3: HGT 3 4
      {2'd0, 6'd4}: word_o = 40'h6000000000;   // keygen 4: SDL
      {2'd0, 6'd5}: word_o = 40'h7000000000;   // keygen 5: RUN 0
      {2'd0, 6'd6}: word_o = 40'h2312180000;   // keygen 6: STP 3 0 144 12
      {2'd0, 6'd7}: word_o = 40'h2418180000;   // keygen 7: STP 4 0 192 12
      {2'd0, 6'd8}: word_o = 40'h251e180000;   // keygen 8: STP 5 0 240 12
      {2'd0, 6'd9}: word_o = 40'h8720000000;   // keygen 9: WR32 3 288
      {2'd0, 6'd10}: word_o = 40'hb480000000;   // keygen 10: BGS 18
      {2'd0, 6'd11}: word_o = 40'h2000180000;   // keygen 11: STP 0 0 0 12
      {2'd0, 6'd12}: word_o = 40'h2106180000;   // keygen 12: STP 1 0 48 12
      {2'd0, 6'd13}: word_o = 40'h220c180000;   // keygen 13: STP 2 0 96 12
      {2'd0, 6'd14}: word_o = 40'hc000000000;   // keygen 14: JN
      {2'd0, 6'd15}: word_o = 40'h8f24000000;   // keygen 15: WR32 7 292
      {2'd0, 6'd16}: word_o = 40'h8328000000;   // keygen 16: WR32 1 296
      {2'd0, 6'd17}: word_o = 40'h0000000000;   // keygen 17: END
      {2'd0, 6'd18}: word_o = 40'h3250000000;   // keygen 18: HST 0 1184
      {2'd0, 6'd19}: word_o = 40'h40904a0000;   // keygen 19: HFD 0 144 148
      {2'd0, 6'd20}: word_o = 40'h5e00000000;   // keygen 20: HGT 7 0
      {2'd0, 6'd21}: word_o = 40'h0000000000;   // keygen 21: END
      {2'd1, 6'd0}: word_o = 40'hb4c0000000;   // encaps 0: BGS 19
      {2'd1, 6'd1}: word_o = 40'h9720000000;   // encaps 1: RD32 3 288
      {2'd1, 6'd2}: word_o = 40'h1712180000;   // encaps 2: LDP 7 0 144 12
      {2'd1, 6'd3}: word_o = 40'hc000000000;   // encaps 3: JN
      {2'd1, 6'd4}: word_o = 40'h3420000000;   // encaps 4: HST 1 64
      {2'd1, 6'd5}: word_o = 40'h4608020000;   // encaps 5: HFD 3 8 4
      {2'd1, 6'd6}: word_o = 40'h461c020000;   // encaps 6: HFD 3 28 4
      {2'd1, 6'd7}: word_o = 40'h5b00000000;   // encaps 7: HGT 5 4
      {2'd1, 6'd8}: word_o = 40'h6000000000;   // encaps 8: SDL
      {2'd1, 6'd9}: word_o = 40'hd6c0000000;   // encaps 9: RUNS 1 2816
      {2'd1, 6'd10}: word_o = 40'h1818180000;   // encaps 10: LDP 8 0 192 12
      {2'd1, 6'd11}: word_o = 40'h191e180000;   // encaps 11: LDP 9 0 240 12
      {2'd1, 6'd12}: word_o = 40'h1bc1000000;   // encaps 12: LDP 11 3 8 1
      {2'd1, 6'd13}: word_o = 40'he000000000;   // encaps 13: RUNJ
      {2'd1, 6'd14}: word_o = 40'h2340100000;   // encaps 14: STP 3 1 0 10
      {2'd1, 6'd15}: word_o = 40'h2445100000;   // encaps 15: STP 4 1 40 10
      {2'd1, 6'd16}: word_o = 40'h254a100000;   // encaps 16: STP 5 1 80 10
      {2'd1, 6'd17}: word_o = 40'h2a4f080000;   // encaps 17: STP 10 1 120 4
      {2'd1, 6'd18}: word_o = 40'h0000000000;   // encaps 18: END
      {2'd1, 6'd19}: word_o = 40'h3250000000;   // encaps 19: HST 0 1184
      {2'd1, 6'd20}: word_o = 40'h40904a0000;   // encaps 20: HFD 0 144 148
      {2'd1, 6'd21}: word_o = 40'h5e00000000;   // encaps 21: HGT 7 0
      {2'd1, 6'd22}: word_o = 40'h0000000000;   // encaps 22: END
      {2'd2, 6'd0}: word_o = 40'hb780000000;   // decaps 0: BGS 30
      {2'd2, 6'd1}: word_o = 40'h1340100000;   // decaps 1: LDP 3 1 0 10
      {2'd2, 6'd2}: word_o = 40'hd90dc00000;   // decaps 2: RUNS 2 1079
      {2'd2, 6'd3}: word_o = 40'h1445100000;   // decaps 3: LDP 4 1 40 10
      {2'd2, 6'd4}: word_o = 40'h154a100000;   // decaps 4: LDP 5 1 80 10
      {2'd2, 6'd5}: word_o = 40'h1000180000;   // decaps 5: LDP 0 0 0 12
      {2'd2, 6'd6}: word_o = 40'h1106180000;   // decaps 6: LDP 1 0 48 12
      {2'd2, 6'd7}: word_o = 40'h120c180000;   // decaps 7: LDP 2 0 96 12
      {2'd2, 6'd8}: word_o = 40'h1a4f080000;   // decaps 8: LDP 10 1 120 4
      {2'd2, 6'd9}: word_o = 40'he000000000;   // decaps 9: RUNJ
      {2'd2, 6'd10}: word_o = 40'h2ac1000000;   // decaps 10: STP 10 3 8 1
      {2'd2, 6'd11}: word_o = 40'hc000000000;   // decaps 11: JN
      {2'd2, 6'd12}: word_o = 40'h3420000000;   // decaps 12: HST 1 64
      {2'd2, 6'd13}: word_o = 40'h4608020000;   // decaps 13: HFD 3 8 4
      {2'd2, 6'd14}: word_o = 40'h4124020000;   // decaps 14: HFD 0 292 4
      {2'd2, 6'd15}: word_o = 40'h5b00000000;   // decaps 15: HGT 5 4
      {2'd2, 6'd16}: word_o = 40'h9720000000;   // decaps 16: RD32 3 288
      {2'd2, 6'd17}: word_o = 40'h6000000000;   // decaps 17: SDL
      {2'd2, 6'd18}: word_o = 40'hd6e0000000;   // decaps 18: RUNS 1 2944
      {2'd2, 6'd19}: word_o = 40'h1712180000;   // decaps 19: LDP 7 0 144 12
      {2'd2, 6'd20}: word_o = 40'h1818180000;   // decaps 20: LDP 8 0 192 12
      {2'd2, 6'd21}: word_o = 40'h191e180000;   // decaps 21: LDP 9 0 240 12
      {2'd2, 6'd22}: word_o = 40'h1bc1000000;   // decaps 22: LDP 11 3 8 1
      {2'd2, 6'd23}: word_o = 40'he000000000;   // decaps 23: RUNJ
      {2'd2, 6'd24}: word_o = 40'h2380100000;   // decaps 24: STP 3 2 0 10
      {2'd2, 6'd25}: word_o = 40'h2485100000;   // decaps 25: STP 4 2 40 10
      {2'd2, 6'd26}: word_o = 40'h258a100000;   // decaps 26: STP 5 2 80 10
      {2'd2, 6'd27}: word_o = 40'h2a8f080000;   // decaps 27: STP 10 2 120 4
      {2'd2, 6'd28}: word_o = 40'ha000000000;   // decaps 28: CMP
      {2'd2, 6'd29}: word_o = 40'h0000000000;   // decaps 29: END
      {2'd2, 6'd30}: word_o = 40'h3a30000000;   // decaps 30: HST 2 1120
      {2'd2, 6'd31}: word_o = 40'h4128020000;   // decaps 31: HFD 0 296 4
      {2'd2, 6'd32}: word_o = 40'h4200440000;   // decaps 32: HFD 1 0 136
      {2'd2, 6'd33}: word_o = 40'h5c00000000;   // decaps 33: HGT 6 0
      {2'd2, 6'd34}: word_o = 40'h0000000000;   // decaps 34: END
      default: word_o = 40'd0;
    endcase
  end

endmodule
`default_nettype wire
