`default_nettype none
`timescale 1ns/1ps
// rtl/sched/gamma_rom.sv
// GENERATED by scripts/gen_kpke_sched_roms.py from tb/golden/primitives.py (_GAMMA, ZETA=17, Q=3329). Do not hand-edit.
// gamma_o = zeta^(2 * BitRev7(addr_i) + 1) mod q: the constant of BaseCaseMultiply for coefficient pair addr_i (FIPS 203 Algorithm 11).

module gamma_rom (
    input  wire  [6:0]  addr_i,
    output logic [11:0] gamma_o
);

  always_comb begin
    case (addr_i)
      7'd0  : gamma_o = 12'd17;
      7'd1  : gamma_o = 12'd3312;
      7'd2  : gamma_o = 12'd2761;
      7'd3  : gamma_o = 12'd568;
      7'd4  : gamma_o = 12'd583;
      7'd5  : gamma_o = 12'd2746;
      7'd6  : gamma_o = 12'd2649;
      7'd7  : gamma_o = 12'd680;
      7'd8  : gamma_o = 12'd1637;
      7'd9  : gamma_o = 12'd1692;
      7'd10 : gamma_o = 12'd723;
      7'd11 : gamma_o = 12'd2606;
      7'd12 : gamma_o = 12'd2288;
      7'd13 : gamma_o = 12'd1041;
      7'd14 : gamma_o = 12'd1100;
      7'd15 : gamma_o = 12'd2229;
      7'd16 : gamma_o = 12'd1409;
      7'd17 : gamma_o = 12'd1920;
      7'd18 : gamma_o = 12'd2662;
      7'd19 : gamma_o = 12'd667;
      7'd20 : gamma_o = 12'd3281;
      7'd21 : gamma_o = 12'd48;
      7'd22 : gamma_o = 12'd233;
      7'd23 : gamma_o = 12'd3096;
      7'd24 : gamma_o = 12'd756;
      7'd25 : gamma_o = 12'd2573;
      7'd26 : gamma_o = 12'd2156;
      7'd27 : gamma_o = 12'd1173;
      7'd28 : gamma_o = 12'd3015;
      7'd29 : gamma_o = 12'd314;
      7'd30 : gamma_o = 12'd3050;
      7'd31 : gamma_o = 12'd279;
      7'd32 : gamma_o = 12'd1703;
      7'd33 : gamma_o = 12'd1626;
      7'd34 : gamma_o = 12'd1651;
      7'd35 : gamma_o = 12'd1678;
      7'd36 : gamma_o = 12'd2789;
      7'd37 : gamma_o = 12'd540;
      7'd38 : gamma_o = 12'd1789;
      7'd39 : gamma_o = 12'd1540;
      7'd40 : gamma_o = 12'd1847;
      7'd41 : gamma_o = 12'd1482;
      7'd42 : gamma_o = 12'd952;
      7'd43 : gamma_o = 12'd2377;
      7'd44 : gamma_o = 12'd1461;
      7'd45 : gamma_o = 12'd1868;
      7'd46 : gamma_o = 12'd2687;
      7'd47 : gamma_o = 12'd642;
      7'd48 : gamma_o = 12'd939;
      7'd49 : gamma_o = 12'd2390;
      7'd50 : gamma_o = 12'd2308;
      7'd51 : gamma_o = 12'd1021;
      7'd52 : gamma_o = 12'd2437;
      7'd53 : gamma_o = 12'd892;
      7'd54 : gamma_o = 12'd2388;
      7'd55 : gamma_o = 12'd941;
      7'd56 : gamma_o = 12'd733;
      7'd57 : gamma_o = 12'd2596;
      7'd58 : gamma_o = 12'd2337;
      7'd59 : gamma_o = 12'd992;
      7'd60 : gamma_o = 12'd268;
      7'd61 : gamma_o = 12'd3061;
      7'd62 : gamma_o = 12'd641;
      7'd63 : gamma_o = 12'd2688;
      7'd64 : gamma_o = 12'd1584;
      7'd65 : gamma_o = 12'd1745;
      7'd66 : gamma_o = 12'd2298;
      7'd67 : gamma_o = 12'd1031;
      7'd68 : gamma_o = 12'd2037;
      7'd69 : gamma_o = 12'd1292;
      7'd70 : gamma_o = 12'd3220;
      7'd71 : gamma_o = 12'd109;
      7'd72 : gamma_o = 12'd375;
      7'd73 : gamma_o = 12'd2954;
      7'd74 : gamma_o = 12'd2549;
      7'd75 : gamma_o = 12'd780;
      7'd76 : gamma_o = 12'd2090;
      7'd77 : gamma_o = 12'd1239;
      7'd78 : gamma_o = 12'd1645;
      7'd79 : gamma_o = 12'd1684;
      7'd80 : gamma_o = 12'd1063;
      7'd81 : gamma_o = 12'd2266;
      7'd82 : gamma_o = 12'd319;
      7'd83 : gamma_o = 12'd3010;
      7'd84 : gamma_o = 12'd2773;
      7'd85 : gamma_o = 12'd556;
      7'd86 : gamma_o = 12'd757;
      7'd87 : gamma_o = 12'd2572;
      7'd88 : gamma_o = 12'd2099;
      7'd89 : gamma_o = 12'd1230;
      7'd90 : gamma_o = 12'd561;
      7'd91 : gamma_o = 12'd2768;
      7'd92 : gamma_o = 12'd2466;
      7'd93 : gamma_o = 12'd863;
      7'd94 : gamma_o = 12'd2594;
      7'd95 : gamma_o = 12'd735;
      7'd96 : gamma_o = 12'd2804;
      7'd97 : gamma_o = 12'd525;
      7'd98 : gamma_o = 12'd1092;
      7'd99 : gamma_o = 12'd2237;
      7'd100: gamma_o = 12'd403;
      7'd101: gamma_o = 12'd2926;
      7'd102: gamma_o = 12'd1026;
      7'd103: gamma_o = 12'd2303;
      7'd104: gamma_o = 12'd1143;
      7'd105: gamma_o = 12'd2186;
      7'd106: gamma_o = 12'd2150;
      7'd107: gamma_o = 12'd1179;
      7'd108: gamma_o = 12'd2775;
      7'd109: gamma_o = 12'd554;
      7'd110: gamma_o = 12'd886;
      7'd111: gamma_o = 12'd2443;
      7'd112: gamma_o = 12'd1722;
      7'd113: gamma_o = 12'd1607;
      7'd114: gamma_o = 12'd1212;
      7'd115: gamma_o = 12'd2117;
      7'd116: gamma_o = 12'd1874;
      7'd117: gamma_o = 12'd1455;
      7'd118: gamma_o = 12'd1029;
      7'd119: gamma_o = 12'd2300;
      7'd120: gamma_o = 12'd2110;
      7'd121: gamma_o = 12'd1219;
      7'd122: gamma_o = 12'd2935;
      7'd123: gamma_o = 12'd394;
      7'd124: gamma_o = 12'd885;
      7'd125: gamma_o = 12'd2444;
      7'd126: gamma_o = 12'd2154;
      7'd127: gamma_o = 12'd1175;
      default: gamma_o = 12'd0;
    endcase
  end

endmodule
`default_nettype wire
