`default_nettype none
`timescale 1ns/1ps
// rtl/sched/kpke_prog_rom.sv
// GENERATED by scripts/gen_kpke_sched_roms.py from tb/golden/kpke_sched_model.py (PROGRAMS). Do not hand-edit.
// Operation word: {opc[2:0], first, last, dst[4:0], a[4:0], b[4:0]}; opc 0 END, 1 NTT, 2 INTT, 3 PWM, 4 ADD, 5 SUB.
// Programs: 0 K-PKE.KeyGen arithmetic, 1 K-PKE.Encrypt arithmetic, 2 K-PKE.Decrypt arithmetic. Unlisted addresses return END.

module kpke_prog_rom (
    input  wire  [1:0]    prog_i,
    input  wire  [5:0]    pc_i,
    output logic [19:0]   op_o
);

  always_comb begin
    case ({prog_i, pc_i})
      {2'd0, 6'd0}: op_o = {3'd1, 1'b0, 1'b0, 5'd9, 5'd0, 5'd0};   // keygen 0
      {2'd0, 6'd1}: op_o = {3'd1, 1'b0, 1'b0, 5'd10, 5'd0, 5'd0};   // keygen 1
      {2'd0, 6'd2}: op_o = {3'd1, 1'b0, 1'b0, 5'd11, 5'd0, 5'd0};   // keygen 2
      {2'd0, 6'd3}: op_o = {3'd1, 1'b0, 1'b0, 5'd12, 5'd0, 5'd0};   // keygen 3
      {2'd0, 6'd4}: op_o = {3'd1, 1'b0, 1'b0, 5'd13, 5'd0, 5'd0};   // keygen 4
      {2'd0, 6'd5}: op_o = {3'd1, 1'b0, 1'b0, 5'd14, 5'd0, 5'd0};   // keygen 5
      {2'd0, 6'd6}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd0, 5'd9};   // keygen 6
      {2'd0, 6'd7}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd1, 5'd10};   // keygen 7
      {2'd0, 6'd8}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd2, 5'd11};   // keygen 8
      {2'd0, 6'd9}: op_o = {3'd4, 1'b0, 1'b0, 5'd12, 5'd15, 5'd12};   // keygen 9
      {2'd0, 6'd10}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd3, 5'd9};   // keygen 10
      {2'd0, 6'd11}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd4, 5'd10};   // keygen 11
      {2'd0, 6'd12}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd5, 5'd11};   // keygen 12
      {2'd0, 6'd13}: op_o = {3'd4, 1'b0, 1'b0, 5'd13, 5'd15, 5'd13};   // keygen 13
      {2'd0, 6'd14}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd6, 5'd9};   // keygen 14
      {2'd0, 6'd15}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd7, 5'd10};   // keygen 15
      {2'd0, 6'd16}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd8, 5'd11};   // keygen 16
      {2'd0, 6'd17}: op_o = {3'd4, 1'b0, 1'b0, 5'd14, 5'd15, 5'd14};   // keygen 17
      {2'd0, 6'd18}: op_o = {3'd0, 1'b0, 1'b0, 5'd0, 5'd0, 5'd0};   // keygen 18
      {2'd1, 6'd0}: op_o = {3'd1, 1'b0, 1'b0, 5'd9, 5'd0, 5'd0};   // encrypt 0
      {2'd1, 6'd1}: op_o = {3'd1, 1'b0, 1'b0, 5'd10, 5'd0, 5'd0};   // encrypt 1
      {2'd1, 6'd2}: op_o = {3'd1, 1'b0, 1'b0, 5'd11, 5'd0, 5'd0};   // encrypt 2
      {2'd1, 6'd3}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd0, 5'd9};   // encrypt 3
      {2'd1, 6'd4}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd3, 5'd10};   // encrypt 4
      {2'd1, 6'd5}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd6, 5'd11};   // encrypt 5
      {2'd1, 6'd6}: op_o = {3'd2, 1'b0, 1'b0, 5'd15, 5'd0, 5'd0};   // encrypt 6
      {2'd1, 6'd7}: op_o = {3'd4, 1'b0, 1'b0, 5'd12, 5'd15, 5'd12};   // encrypt 7
      {2'd1, 6'd8}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd1, 5'd9};   // encrypt 8
      {2'd1, 6'd9}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd4, 5'd10};   // encrypt 9
      {2'd1, 6'd10}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd7, 5'd11};   // encrypt 10
      {2'd1, 6'd11}: op_o = {3'd2, 1'b0, 1'b0, 5'd15, 5'd0, 5'd0};   // encrypt 11
      {2'd1, 6'd12}: op_o = {3'd4, 1'b0, 1'b0, 5'd13, 5'd15, 5'd13};   // encrypt 12
      {2'd1, 6'd13}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd2, 5'd9};   // encrypt 13
      {2'd1, 6'd14}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd5, 5'd10};   // encrypt 14
      {2'd1, 6'd15}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd8, 5'd11};   // encrypt 15
      {2'd1, 6'd16}: op_o = {3'd2, 1'b0, 1'b0, 5'd15, 5'd0, 5'd0};   // encrypt 16
      {2'd1, 6'd17}: op_o = {3'd4, 1'b0, 1'b0, 5'd14, 5'd15, 5'd14};   // encrypt 17
      {2'd1, 6'd18}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd16, 5'd9};   // encrypt 18
      {2'd1, 6'd19}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd17, 5'd10};   // encrypt 19
      {2'd1, 6'd20}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd18, 5'd11};   // encrypt 20
      {2'd1, 6'd21}: op_o = {3'd2, 1'b0, 1'b0, 5'd15, 5'd0, 5'd0};   // encrypt 21
      {2'd1, 6'd22}: op_o = {3'd4, 1'b0, 1'b0, 5'd19, 5'd15, 5'd19};   // encrypt 22
      {2'd1, 6'd23}: op_o = {3'd4, 1'b0, 1'b0, 5'd19, 5'd19, 5'd20};   // encrypt 23
      {2'd1, 6'd24}: op_o = {3'd0, 1'b0, 1'b0, 5'd0, 5'd0, 5'd0};   // encrypt 24
      {2'd2, 6'd0}: op_o = {3'd1, 1'b0, 1'b0, 5'd12, 5'd0, 5'd0};   // decrypt 0
      {2'd2, 6'd1}: op_o = {3'd1, 1'b0, 1'b0, 5'd13, 5'd0, 5'd0};   // decrypt 1
      {2'd2, 6'd2}: op_o = {3'd1, 1'b0, 1'b0, 5'd14, 5'd0, 5'd0};   // decrypt 2
      {2'd2, 6'd3}: op_o = {3'd3, 1'b1, 1'b0, 5'd15, 5'd9, 5'd12};   // decrypt 3
      {2'd2, 6'd4}: op_o = {3'd3, 1'b0, 1'b0, 5'd15, 5'd10, 5'd13};   // decrypt 4
      {2'd2, 6'd5}: op_o = {3'd3, 1'b0, 1'b1, 5'd15, 5'd11, 5'd14};   // decrypt 5
      {2'd2, 6'd6}: op_o = {3'd2, 1'b0, 1'b0, 5'd15, 5'd0, 5'd0};   // decrypt 6
      {2'd2, 6'd7}: op_o = {3'd5, 1'b0, 1'b0, 5'd19, 5'd19, 5'd15};   // decrypt 7
      {2'd2, 6'd8}: op_o = {3'd0, 1'b0, 1'b0, 5'd0, 5'd0, 5'd0};   // decrypt 8
      default: op_o = 20'd0;
    endcase
  end

endmodule
`default_nettype wire
