`default_nettype none
`timescale 1ns/1ps
// formal/phase09m-optimisation/9i4/mlkem_core4_formal_top.sv (Phase 9I item 4, test_plan_9i4.md V8: the 9f1b proof for rtl/mlkem/mlkem_core4.sv; new state S_RUNJ, the engine start also for RUNS, E1 for the interlock register and the sticky done flag, P1-P3 below)
// original header follows:
// formal/phase09m-optimisation/9f1b/mlkem_core4_formal_top.sv
// Phase 9F S1b (evidence/phase9m/batch1/9f1b/test_plan_9f1b.md V7): the 9c controller proof (E1, S1-S7) for rtl/mlkem/mlkem_core3.sv (two-byte tasks, background hash sidecar), extended with B1-B6 of the sidecar. Derived from formal/phase09-integration/9c/mlkem_core_formal_top.sv; the module is renamed.
// Added: E1 for the sidecar registers; B1 the hash unit has one owner (the main controller is never in HFD or HGT, and never starts the hash, while a job runs); B2 done_o only when the sidecar is idle; B3 JN, BGS and END do not advance while a job runs; B4 a write that the main controller does not make is a digest write of the sidecar into the register file; B5 the sidecar read address stays inside its memory; B6 the sidecar counters. S3 and S6 now talk about the main controller's own write (fw_*); S4 treats the start strobe of the hash by owner.
// Phase 9c (evidence/phase09/9c/test_plan_9c.md, Amendment A2): control properties of the controller rtl/mlkem/mlkem_core.sv with the sub-blocks replaced by protocol stubs (stubs_9c.sv); the memories, the register file and the ROM are the real ones.
// Two copies of the core (A and B) run side by side. They get the same control inputs (op, start, host strobe and address, and the stubs' control signals f_c*, assumed equal) and DIFFERENT data (the host data, the stubs' data signals f_d*, the contents of the memories).
//   E1  non-interference: every control register of A equals that of B at all times, i.e. the sequence of states, the program counter, the counters and the strobes do not depend on any data (the proof of "no branch, address or count depends on a secret", for the controller)
//   S1  state and program counter in range
//   S2  busy_o is exactly "not idle"; done_o only when idle
//   S3  nothing writes a memory in the states LDP, HFD, SDL, RUN, CMP, FETCH, DISP: the host cannot write while busy
//   S4  the start strobes of the sub-blocks occur only in DISP, one at most, and only for their own micro-operation
//   S5  the engine host port is written only in LDP; the seed port only in SDL with a step below 8
//   S6  addresses generated by the controller itself (WR32, RD32, HGT, CMPK writes; HFD and RD32 reads) stay inside the memory they address
//   S7  step counters stay in range
// Control and range only; values are covered by simulation against the golden model. Free stub signals are `wire` (see stubs_9c.sv).

module mlkem_core4_formal_top #(
    parameter bit P1_ON = 1'b1   // 1: check P1 (a bounded check; it is not inductive without an invariant on the program position); the induction proof runs with P1_ON = 0
) (
    input  wire         clk_i,
    input  wire         rst_ni,
    input  wire  [1:0]  op_i,
    input  wire         start_i,
    input  wire         h_we_i,
    input  wire  [11:0] h_addr_i,
    input  wire  [63:0] h_wdata_a_i,
    input  wire  [63:0] h_wdata_b_i,
    output wire         busy_a_o,
    output wire         done_a_o,
    output wire         busy_b_o,
    output wire         done_b_o,
    output wire  [63:0] h_rdata_a_o,
    output wire  [63:0] h_rdata_b_o
);

  // Phase 9M (test_plan_9m1.md): the load / store tasks sit in generate blocks of the core (CODEC_W2); -D W2 proves the core with the two-byte tasks (their stubs in formal/phase09m-optimisation/9m1/stubs_9m1.sv)
  `define LDP g_ld2.u_ld
  `define STP g_st2.u_st

  mlkem_core4 #(.CODEC_W2(1'b1), .SMP_C5(1'b0), .HASH_C5(1'b0)) u_a (.clk_i(clk_i), .rst_ni(rst_ni), .op_i(op_i), .start_i(start_i), .busy_o(busy_a_o), .done_o(done_a_o), .h_we_i(h_we_i), .h_addr_i(h_addr_i), .h_wdata_i(h_wdata_a_i), .h_rdata_o(h_rdata_a_o));
  mlkem_core4 #(.CODEC_W2(1'b1), .SMP_C5(1'b0), .HASH_C5(1'b0)) u_b (.clk_i(clk_i), .rst_ni(rst_ni), .op_i(op_i), .start_i(start_i), .busy_o(busy_b_o), .done_o(done_b_o), .h_we_i(h_we_i), .h_addr_i(h_addr_i), .h_wdata_i(h_wdata_b_i), .h_rdata_o(h_rdata_b_o));

`ifdef FORMAL
  logic f_init = 1'b1;
  always_ff @(posedge clk_i) f_init <= 1'b0;
  always_comb if (f_init) assume (!rst_ni);

  // the control signals of the stubs are the same in both copies; their data signals are free in each copy
  always_comb begin
    assume (u_a.u_eng.f_cfin == u_b.u_eng.f_cfin);
    assume (u_a.u_eng.f_cwrdy == u_b.u_eng.f_cwrdy);
    assume (u_a.u_hash.f_cinr == u_b.u_hash.f_cinr);
    assume (u_a.u_hash.f_cov == u_b.u_hash.f_cov);
    assume (u_a.u_hash.f_ccl == u_b.u_hash.f_ccl);
    assume (u_a.u_hash.f_cfin == u_b.u_hash.f_cfin);
    assume (u_a.u_fo.f_cfin == u_b.u_fo.f_cfin);
    assume (u_a.`LDP.f_cfin == u_b.`LDP.f_cfin);
    assume (u_a.`LDP.f_creq == u_b.`LDP.f_creq);
    assume (u_a.`LDP.f_cwe == u_b.`LDP.f_cwe);
    assume (u_a.`LDP.f_cadr == u_b.`LDP.f_cadr);
    assume (u_a.`LDP.f_cslot == u_b.`LDP.f_cslot);
    assume (u_a.`LDP.f_ctadr == u_b.`LDP.f_ctadr);
    assume (u_a.`STP.f_cfin == u_b.`STP.f_cfin);
    assume (u_a.`STP.f_cwe == u_b.`STP.f_cwe);
    assume (u_a.`STP.f_cadr == u_b.`STP.f_cadr);
    assume (u_a.`STP.f_cslot == u_b.`STP.f_cslot);
    assume (u_a.`STP.f_ctadr == u_b.`STP.f_ctadr);
  end

  localparam logic [2:0] B_IDLE = 3'd0, B_FETCH = 3'd1, B_DISP = 3'd2, B_HFD = 3'd3, B_HGT = 3'd4;
  localparam logic [3:0] S_IDLE = 4'd0, S_FETCH = 4'd1, S_DISP = 4'd2, S_LDP = 4'd3, S_STP = 4'd4, S_HFD = 4'd5, S_HGT = 4'd6, S_SDL = 4'd7, S_RUN = 4'd8, S_WR32 = 4'd9, S_RD32 = 4'd10, S_CMP = 4'd11, S_CMPK = 4'd12, S_RUNJ = 4'd13;
  wire [3:0] sa = 4'(u_a.state_q);

  logic f_past_valid = 1'b0;
  always_ff @(posedge clk_i) f_past_valid <= 1'b1;

  always_ff @(posedge clk_i) begin
    if (rst_ni) begin
      // E1: all control registers equal
      assert (u_a.pend_q == u_b.pend_q && u_a.eng_dn_q == u_b.eng_dn_q);   // item 4: the interlock register and the sticky done flag are control
      assert (u_a.state_q == u_b.state_q);
      assert (u_a.op_q == u_b.op_q);
      assert (u_a.pc_q == u_b.pc_q);
      if (sa != S_IDLE && sa != S_FETCH) assert (u_a.ins_q == u_b.ins_q);   // ins_q is loaded in FETCH (not reset): before that it is stale in both copies
      assert (u_a.done_q == u_b.done_q);
      assert (u_a.rd_rgn_q == u_b.rd_rgn_q);
      assert (u_a.fd_issued_q == u_b.fd_issued_q);
      assert (u_a.fd_cons_q == u_b.fd_cons_q);
      assert (u_a.fd_valid_q == u_b.fd_valid_q);
      assert (u_a.hold_v_q == u_b.hold_v_q);
      assert (u_a.hg_w_q == u_b.hg_w_q);
      assert (u_a.k_q == u_b.k_q);
      assert (u_a.cm_issued_q == u_b.cm_issued_q);
      assert (u_a.cm_valid_q == u_b.cm_valid_q);
      assert (u_a.bs_q == u_b.bs_q && u_a.bpc_q == u_b.bpc_q && u_a.bgq_q == u_b.bgq_q);
      if (u_a.bs_q == B_DISP || u_a.bs_q == B_HFD || u_a.bs_q == B_HGT) assert (u_a.bins_q == u_b.bins_q);
      assert (u_a.bfd_issued_q == u_b.bfd_issued_q && u_a.bfd_cons_q == u_b.bfd_cons_q && u_a.bfd_valid_q == u_b.bfd_valid_q && u_a.bhold_v_q == u_b.bhold_v_q && u_a.bhg_w_q == u_b.bhg_w_q);
      assert (busy_a_o == busy_b_o && done_a_o == done_b_o);
      // the control state of the stubs is equal too (supporting invariant: a stub's busy and done flags depend on control only)
      assert (u_a.u_eng.busy_q == u_b.u_eng.busy_q && u_a.u_eng.done_q == u_b.u_eng.done_q);
      assert (u_a.u_hash.busy_q == u_b.u_hash.busy_q && u_a.u_hash.done_q == u_b.u_hash.done_q);
      assert (u_a.u_fo.busy_q == u_b.u_fo.busy_q && u_a.u_fo.done_q == u_b.u_fo.done_q);
      assert (u_a.`LDP.busy_q == u_b.`LDP.busy_q && u_a.`LDP.done_q == u_b.`LDP.done_q);
      assert (u_a.`STP.busy_q == u_b.`STP.busy_q && u_a.`STP.done_q == u_b.`STP.done_q);
      assert (u_a.wr_en == u_b.wr_en && u_a.wr_rgn == u_b.wr_rgn && u_a.wr_addr == u_b.wr_addr && u_a.rd_addr == u_b.rd_addr);
      // S1
      assert (sa <= S_RUNJ);
      assert (u_a.pc_q < 6'd36);
      assert (u_a.bpc_q < 6'd36);
      // S2
      assert (busy_a_o == (sa != S_IDLE));
      if (done_a_o) assert (!busy_a_o);
      // S3
      if (sa == S_LDP || sa == S_HFD || sa == S_SDL || sa == S_RUN || sa == S_RUNJ || sa == S_CMP || sa == S_FETCH || sa == S_DISP) assert (!u_a.fw_en);
      // S4
      assert (!(u_a.ld_start && u_a.st_start) && !(u_a.ld_start && u_a.m_hs_start) && !(u_a.ld_start && u_a.eng_start) && !(u_a.ld_start && u_a.fo_start));
      assert (!(u_a.st_start && u_a.m_hs_start) && !(u_a.st_start && u_a.eng_start) && !(u_a.st_start && u_a.fo_start));
      assert (!(u_a.m_hs_start && u_a.eng_start) && !(u_a.m_hs_start && u_a.fo_start) && !(u_a.eng_start && u_a.fo_start));
      if (u_a.ld_start || u_a.st_start || u_a.m_hs_start || u_a.eng_start || u_a.fo_start) assert (sa == S_DISP);
      assert (u_a.hs_start == (u_a.m_hs_start || u_a.bg_hs_start));
      assert (!(u_a.m_hs_start && u_a.bg_hs_start));
      if (u_a.ld_start) assert (u_a.opc == 4'd1);
      if (u_a.st_start) assert (u_a.opc == 4'd2);
      if (u_a.m_hs_start) assert (u_a.opc == 4'd3);
      if (u_a.eng_start) assert (u_a.opc == 4'd7 || u_a.opc == 4'd13);
      if (u_a.fo_start) assert (u_a.opc == 4'd10);
      // S5
      if (u_a.eng_tb_we) assert (sa == S_LDP);
      if (u_a.eng_seed_we) assert (sa == S_SDL && u_a.k_q < 4'd8);
      // supporting invariant: the stored micro-instruction is the ROM word of the current program counter (the program counter is stable while an operation runs)
      if (sa != S_IDLE && sa != S_FETCH) assert (u_a.ins_q == u_a.rom_w);
      // supporting invariants: the state of a running operation matches the opcode of the stored micro-instruction
      if (sa == S_LDP) assert (u_a.opc == 4'd1);
      if (sa == S_STP) assert (u_a.opc == 4'd2);
      if (sa == S_HFD) assert (u_a.opc == 4'd4);
      if (sa == S_HGT) assert (u_a.opc == 4'd5);
      if (sa == S_SDL) assert (u_a.opc == 4'd6);
      if (sa == S_RUN) assert (u_a.opc == 4'd7);
      if (sa == S_RUNJ) assert (u_a.opc == 4'd14);
      if (sa == S_WR32) assert (u_a.opc == 4'd8);
      if (sa == S_RD32) assert (u_a.opc == 4'd9);
      if (sa == S_CMP || sa == S_CMPK) assert (u_a.opc == 4'd10);
      // S7
      if (sa == S_SDL) assert (u_a.k_q <= 4'd8);
      if (sa == S_WR32) assert (u_a.k_q <= 4'd4);
      if (sa == S_RD32) assert (u_a.k_q <= 4'd5);
      if (sa == S_CMPK) assert (u_a.k_q <= 4'd4);
      if (sa == S_HFD) begin
        assert (u_a.fd_issued_q <= u_a.f_hnw);
        assert (u_a.fd_issued_q == u_a.fd_cons_q + 9'(u_a.fd_valid_q) + 9'(u_a.hold_v_q));   // words requested = consumed + in flight + held
        assert (!(u_a.fd_valid_q && u_a.hold_v_q));
      end
      if (sa == S_CMP) assert (u_a.cm_issued_q <= 9'd136);
      // S6
      if (sa == S_WR32 && u_a.fw_en) assert (u_a.fw_rgn == 2'd0 && u_a.fw_addr < 9'd300);
      if (sa == S_RD32 && u_a.fw_en) assert (u_a.fw_rgn == 2'd3 && u_a.fw_addr < 9'd32);
      if (sa == S_HGT && u_a.fw_en) assert (u_a.fw_rgn == 2'd3 && u_a.fw_addr < 9'd32);
      if (sa == S_CMPK && u_a.fw_en) assert (u_a.fw_rgn == 2'd3 && u_a.fw_addr < 9'd32);
      if (sa == S_RD32 && u_a.k_q < 4'd4) assert (u_a.rd_addr < 9'd300);
      if (u_a.fd_issue) begin
        case (u_a.f_hsrc)
          3'd0: assert (u_a.rd_addr < 9'd300);
          3'd1, 3'd2: assert (u_a.rd_addr < 9'd136);
          3'd3: assert (u_a.rd_addr < 9'd32);
          default: ;
        endcase
      end
      if (u_a.cm_issue) assert (u_a.rd_addr < 9'd136);
      // sidecar invariants
      if (u_a.bg_own) assert (sa != S_IDLE);          // the main controller does not finish while a job runs (supporting invariant: op_q does not change under the job)
      if (u_a.bs_q == B_DISP || u_a.bs_q == B_HFD || u_a.bs_q == B_HGT) assert (u_a.bins_q == u_a.rom_bw);
      if (u_a.bs_q == B_HFD) assert (u_a.b_opc == 4'd4);
      if (u_a.bs_q == B_HGT) assert (u_a.b_opc == 4'd5);
      if (u_a.bs_q == B_HFD) begin
        assert (u_a.bfd_issued_q <= u_a.b_hnw);
        assert (u_a.bfd_issued_q == u_a.bfd_cons_q + 9'(u_a.bfd_valid_q) + 9'(u_a.bhold_v_q));
        assert (!(u_a.bfd_valid_q && u_a.bhold_v_q));
      end
      // B1 one owner of the hash unit
      assert (!(u_a.bg_own && (sa == S_HFD || sa == S_HGT)));
      // B2
      if (done_a_o) assert (!u_a.bg_own);
      // B7 the main controller's own write is never overridden or lost on the bus
      if (u_a.fw_en) assert (u_a.wr_en && u_a.wr_rgn == u_a.fw_rgn && u_a.wr_addr == u_a.fw_addr && u_a.wr_data == u_a.fw_data);
      // B4 / B5
      if (u_a.wr_en && !u_a.fw_en) assert (u_a.bs_q == B_HGT && u_a.wr_rgn == 2'd3 && u_a.wr_addr < 9'd32);
      if (u_a.bfd_issue) begin
        assert (!u_a.fg_rd_req);
        case (u_a.b_hsrc)
          3'd0: assert (u_a.rd_addr < 9'd300);
          3'd1, 3'd2: assert (u_a.rd_addr < 9'd136);
          3'd3: assert (u_a.rd_addr < 9'd32);
          default: ;
        endcase
      end
      // item 4: P1 the engine is not busy when the controller stores (STP) or downloads seeds (SDL): the programs end every RUNS with a RUNJ before them
      if (P1_ON && (sa == S_STP || sa == S_SDL)) assert (!u_a.u_eng.busy_q);
      // (a property 'pend_q is 0 when idle' fails induction without a supporting invariant on the program position; it is not part of this proof and is stated as not proven)
      // B3 (needs one past cycle)
      if (f_past_valid) begin
        if ($past(sa == S_DISP && (u_a.opc == 4'd0 || u_a.opc == 4'd11 || u_a.opc == 4'd12) && u_a.bg_own)) assert (sa == S_DISP);
      end
      // reachability (anti-vacuity), cover mode only: a digest word of the main controller and of the sidecar can be written, the sidecar can issue a read (depth 200)
`ifdef DEEP
      // a program with a 148-word background job cannot finish before about 260 cycles even with stubs that answer at once (define DEEP, depth 330)
      cover (done_a_o && u_a.op_q == 2'd0);
      cover (done_a_o && u_a.op_q == 2'd1);
`endif
      cover (sa == S_HGT && u_a.hg_take);
      cover (sa == S_LDP && u_a.u_eng.busy_q && u_a.ld_we && u_a.pend_q != 12'd0);   // item 4: a load runs while the engine is busy and a slot is marked
      cover (sa == S_RUNJ && u_a.eng_dn_q);
      cover (u_a.bs_q == B_HGT && u_a.bg_take);
      cover (u_a.bs_q == B_HFD && u_a.bfd_issue);
`ifdef DEEP
      // the longest program (Decaps, 30 micro-operations, two hashes of 136 to 148 words) needs more than 260 cycles even with stubs that finish at once (depth 480, define DEEP)
      cover (done_a_o && u_a.op_q == 2'd2);
      cover (sa == S_CMPK);
`endif
    end
  end
`endif

endmodule
`default_nettype wire
