#!/usr/bin/env python3
"""scripts/gen_keccak_consts.py

Phase 7 (docs/evidence/phase07-keccak/test_plan.md V3): generates rtl/keccak/keccak_pkg.sv from the verified golden model (tb/golden/keccak.py), never hand-typed:
  keccak_rc(ir)    the 24 round constants (FIPS 202 Algorithm 5 and 6)
  keccak_rho(i)    the 25 rho rotation offsets of lane i = x + 5y (FIPS 202 Algorithm 2)
The file carries no date, so re-running reproduces it byte for byte; --check compares instead of writing (exit 1 on a difference).
Usage: python3 scripts/gen_keccak_consts.py [--check]
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tb" / "golden"))

from keccak import RC, RHO  # noqa: E402

OUT = ROOT / "rtl" / "keccak" / "keccak_pkg.sv"


def text() -> str:
    rc = "\n".join(f"      5'd{i:<2}: keccak_rc = 64'h{v:016X};" for i, v in enumerate(RC))
    rho = "\n".join(f"      5'd{i:<2}: keccak_rho = 6'd{v};" for i, v in enumerate(RHO))
    return f"""`default_nettype none
`timescale 1ns/1ps
// rtl/keccak/keccak_pkg.sv  (GENERATED by scripts/gen_keccak_consts.py from tb/golden/keccak.py; do not edit by hand)
// Round constants RC[0..23] and rho offsets of lane x + 5y (FIPS 202 Algorithms 2, 5, 6).

package keccak_pkg;

  localparam int LANES  = 25;
  localparam int ROUNDS = 24;

  function automatic logic [63:0] keccak_rc(input logic [4:0] ir);
    case (ir)
{rc}
      default: keccak_rc = 64'h0;
    endcase
  endfunction

  function automatic logic [5:0] keccak_rho(input logic [4:0] i);
    case (i)
{rho}
      default: keccak_rho = 6'd0;
    endcase
  endfunction

endpackage

`default_nettype wire
"""


def main() -> int:
    t = text()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == t
        print(f"{OUT.relative_to(ROOT)}: {'0 differences' if ok else 'DIFFERENT'}; rc {len(RC)} entries, rho {len(RHO)} entries")
        return 0 if ok else 1
    OUT.write_text(t)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
