#!/usr/bin/env bash
# =============================================================================
# CHIP 2026 - AI/EDA tooling setup and verification
# =============================================================================
# Installs ONLY the tools classified "INSTALL NOW" in docs/AI_TOOLING_RESEARCH.md:
#
#   1. OSS CAD Suite (Verilator, Icarus, Yosys+slang, SymbiYosys, solvers, slang)
#   2. Project Python venv (.venv): cocotb, pyslang, pytest  (pinned, tested)
#   3. Claude Code plugin: rtl-agent-team  (project scope)
#
# In `verify` mode it also checks the project's own Claude Code skills (.claude/skills:
# SKILL.md frontmatter + each skill script's --selftest) and GitHub readiness (remote, gh login,
# .venv ignored). For the GitHub first-commit workflow use scripts/setup_github.sh.
#
# Intel Quartus Prime Lite + Cyclone V device support + Questa Starter are also
# INSTALL NOW, but they need a manual download/licence, so this script only
# DETECTS and SMOKE-TESTS them.
#
# Never installed here (see report): GateFlow, FPGA-LSP, systemverilog-lsp,
# weft-mcp, SynthPilot, oh-my-fpga, other MCP servers.
#
# Usage (from the repository root):
#   scripts/setup_tooling.sh check     # report only; changes nothing (default)
#   scripts/setup_tooling.sh install   # install items 1-3, then run verify
#   scripts/setup_tooling.sh verify    # versions + smoke tests + log
#
# Configuration (environment variables, all optional):
#   TOOLS_DIR            where OSS CAD Suite is unpacked   (default: $HOME/tools)
#   OSS_CAD_SUITE_TAG    release tag, e.g. 2026-09-23       (default: latest)
#   OSS_CAD_SUITE_DIR    use an existing unpacked suite     (skips download)
#   QUARTUS_BIN          path to .../quartus/bin            (default: auto-detect)
#   SKIP_QUARTUS_SMOKE=1 skip the Quartus compile smoke test (it takes minutes)
#
# No sudo is used anywhere. Every result is appended to docs/TOOLING_INSTALL_LOG.md
# verbatim; nothing in the log is estimated or typed by hand.
# =============================================================================
set -uo pipefail

MODE="${1:-check}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG="$REPO_ROOT/docs/TOOLING_INSTALL_LOG.md"
ENV_FILE="$REPO_ROOT/scripts/tooling.env"
SMOKE="$REPO_ROOT/scripts/test/smoke"
TOOLS_DIR="${TOOLS_DIR:-$HOME/tools}"
VENV="$REPO_ROOT/.venv"
REQ="$REPO_ROOT/scripts/requirements-dev.txt"

RAT_MARKETPLACE_REPO="babyworm/rtl-agent-team"
RAT_MARKETPLACE_NAME="rtl-agent-marketplace"
RAT_PLUGIN="rtl-agent-team@${RAT_MARKETPLACE_NAME}"

PASS=0; FAIL=0; WARN=0
c_ok()   { printf '\033[32m[ OK ]\033[0m %s\n' "$*"; PASS=$((PASS+1)); log_line "- OK: $*"; }
c_fail() { printf '\033[31m[FAIL]\033[0m %s\n' "$*"; FAIL=$((FAIL+1)); log_line "- FAIL: $*"; }
c_warn() { printf '\033[33m[WARN]\033[0m %s\n' "$*"; WARN=$((WARN+1)); log_line "- WARN: $*"; }
info()   { printf '       %s\n' "$*"; }
log_line() { [ "$MODE" = "check" ] && return 0; mkdir -p "$(dirname "$LOG")"; printf '%s\n' "$*" >> "$LOG"; }
log_block() { # $1 = title, stdin = raw text
  [ "$MODE" = "check" ] && { cat >/dev/null; return 0; }
  { printf '\n<details><summary>%s</summary>\n\n```text\n' "$1"; cat; printf '```\n</details>\n'; } >> "$LOG"
}

# ----------------------------------------------------------------------------- env
load_env() {
  [ -f "$ENV_FILE" ] && . "$ENV_FILE"
  if [ -z "${OSS_CAD_SUITE_DIR:-}" ] && [ -d "$TOOLS_DIR/oss-cad-suite" ]; then
    OSS_CAD_SUITE_DIR="$TOOLS_DIR/oss-cad-suite"
  fi
  # Suite binaries on PATH only. We deliberately do NOT source the suite's
  # `environment` script: it swaps in the suite's own Python, and the project
  # uses a pinned venv instead (tested combination, see report §18).
  [ -n "${OSS_CAD_SUITE_DIR:-}" ] && [ -d "$OSS_CAD_SUITE_DIR/bin" ] && PATH="$OSS_CAD_SUITE_DIR/bin:$PATH"
  if [ -z "${QUARTUS_BIN:-}" ]; then
    if command -v quartus_sh >/dev/null 2>&1; then
      QUARTUS_BIN="$(dirname "$(command -v quartus_sh)")"
    else
      for d in "${QUARTUS_ROOTDIR:-/nonexistent}/bin" \
               "$HOME"/intelFPGA_lite/*/quartus/bin "$HOME"/altera_lite/*/quartus/bin \
               /opt/intelFPGA_lite/*/quartus/bin /opt/altera_lite/*/quartus/bin \
               "$HOME"/intelFPGA/*/quartus/bin /opt/intelFPGA/*/quartus/bin; do
        [ -x "$d/quartus_sh" ] && QUARTUS_BIN="$d"   # last match = newest by glob order
      done
    fi
  fi
  [ -n "${QUARTUS_BIN:-}" ] && PATH="$QUARTUS_BIN:$PATH"
  export PATH
}

write_env() {
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup_tooling.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Source via scripts/env.sh.
OSS_CAD_SUITE_DIR="${OSS_CAD_SUITE_DIR:-}"
OSS_CAD_SUITE_TAG="${OSS_CAD_SUITE_TAG:-}"
QUARTUS_BIN="${QUARTUS_BIN:-}"
EOF
}

# ------------------------------------------------------------------------ install
install_oss_cad_suite() {
  if [ -n "${OSS_CAD_SUITE_DIR:-}" ] && [ -x "$OSS_CAD_SUITE_DIR/bin/yosys" ]; then
    [ -z "${OSS_CAD_SUITE_TAG:-}" ] && [ -f "$OSS_CAD_SUITE_DIR/VERSION" ] && OSS_CAD_SUITE_TAG="$(head -1 "$OSS_CAD_SUITE_DIR/VERSION")"
    c_ok "OSS CAD Suite already present at $OSS_CAD_SUITE_DIR (${OSS_CAD_SUITE_TAG:-version unknown}; not re-downloaded)"; return 0
  fi
  local tag="${OSS_CAD_SUITE_TAG:-}"
  if [ -z "$tag" ]; then
    # Resolve "latest" via the web redirect (not the rate-limited GitHub API).
    tag="$(curl -sI https://github.com/YosysHQ/oss-cad-suite-build/releases/latest \
           | grep -i '^location:' | sed 's#.*/tag/##' | tr -d '\r')"
  fi
  [ -z "$tag" ] && { c_fail "could not resolve an OSS CAD Suite release tag"; return 1; }
  local url="https://github.com/YosysHQ/oss-cad-suite-build/releases/download/${tag}/oss-cad-suite-linux-x64-${tag//-/}.tgz"
  info "Downloading OSS CAD Suite ${tag} (~750 MB) -> $TOOLS_DIR"
  mkdir -p "$TOOLS_DIR"
  if curl -fL --progress-bar "$url" -o "$TOOLS_DIR/oss-cad-suite-${tag}.tgz" \
     && tar xzf "$TOOLS_DIR/oss-cad-suite-${tag}.tgz" -C "$TOOLS_DIR"; then
    rm -f "$TOOLS_DIR/oss-cad-suite-${tag}.tgz"
    OSS_CAD_SUITE_DIR="$TOOLS_DIR/oss-cad-suite"; OSS_CAD_SUITE_TAG="$tag"
    PATH="$OSS_CAD_SUITE_DIR/bin:$PATH"; export PATH
    c_ok "OSS CAD Suite ${tag} installed at $OSS_CAD_SUITE_DIR"
  else
    c_fail "OSS CAD Suite download/extract failed from $url"
  fi
}

install_python_venv() {
  local py; py="$(command -v python3)"
  [ -z "$py" ] && { c_fail "python3 not found"; return 1; }
  if ! "$py" -c 'import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)'; then
    c_fail "python3 >= 3.10 required (found $("$py" --version 2>&1))"; return 1
  fi
  [ -d "$VENV" ] || "$py" -m venv "$VENV" || { c_fail "venv creation failed (Debian/Ubuntu: python3-venv package)"; return 1; }
  if "$VENV/bin/pip" install -q --upgrade pip >/dev/null && "$VENV/bin/pip" install -q -r "$REQ"; then
    c_ok "Python venv ready at .venv ($("$VENV/bin/pip" list 2>/dev/null | grep -iE '^(cocotb|pyslang|pytest) ' | tr -s ' ' | tr '\n' ';'))"
  else
    c_fail "pip install -r scripts/requirements-dev.txt failed"
  fi
}

install_plugins() {
  command -v claude >/dev/null 2>&1 || { c_fail "Claude Code CLI ('claude') not found on PATH"; return 1; }
  if (cd "$REPO_ROOT" && claude plugin list 2>/dev/null) | grep -A3 "gateflow@" | grep -qi "enabled"; then
    c_warn "GateFlow is enabled. It overlaps rtl-agent-team; disable one (see CLAUDE.md)."
  fi
  claude plugin marketplace add "$RAT_MARKETPLACE_REPO" 2>&1 | tail -1 | log_block "marketplace add $RAT_MARKETPLACE_REPO"
  if claude plugin install "$RAT_PLUGIN" --scope project 2>&1 | tee /tmp/rat_install.$$ | tail -1 | grep -q "Successfully"; then
    c_ok "Installed $RAT_PLUGIN (scope: project -> .claude/settings.json)"
  elif grep -qi "already" /tmp/rat_install.$$; then
    c_ok "$RAT_PLUGIN already installed"
  else
    c_fail "plugin install failed:"; cat /tmp/rat_install.$$
  fi
  rm -f /tmp/rat_install.$$
  info "Next, inside Claude Code: run /reload-plugins, then /rtl-agent-team:rat-setup"
  info "  - answer SKIP for SystemC and for 'global deployment' (keep rules in-project)"
  info "  - point it at the OSS CAD Suite tools already on PATH"
}

# ------------------------------------------------------------------------- verify
ver() { # $1 label, $2... command
  local label="$1"; shift
  local out; out="$("$@" 2>&1 | head -1)"
  if [ -n "$out" ] && command -v "$1" >/dev/null 2>&1; then c_ok "$label: $out"; else c_fail "$label not found ($1)"; fi
}

verify_versions() {
  ver "verilator" verilator --version
  ver "iverilog"  iverilog -V
  ver "yosys"     yosys -V
  ver "sby"       sby --help
  ver "slang"     slang --version
  if yosys -m slang -p 'help read_slang' >/dev/null 2>&1; then c_ok "yosys-slang plugin loads (read_slang available)"
  else c_fail "yosys-slang plugin does not load"; fi
  if [ -x "$VENV/bin/python" ]; then
    c_ok "venv: $("$VENV/bin/python" -c 'import cocotb,pyslang,sys;print("python",sys.version.split()[0],"cocotb",cocotb.__version__,"pyslang",pyslang.__version__)' 2>&1)"
  else
    c_fail "project venv missing (.venv) - run: scripts/setup_tooling.sh install"
  fi
}

verify_quartus() {
  if [ -z "${QUARTUS_BIN:-}" ] || [ ! -x "$QUARTUS_BIN/quartus_sh" ]; then
    c_fail "Quartus Prime not found (set QUARTUS_BIN=/path/to/quartus/bin). Manual install required: see report §18."
    return 1
  fi
  quartus_sh --version 2>&1 | log_block "quartus_sh --version"
  c_ok "Quartus: $(quartus_sh --version 2>&1 | grep -m1 -i 'version')"
  for t in quartus_syn quartus_map quartus_fit quartus_asm quartus_sta quartus_pgm quartus_stp qsys-generate; do
    if command -v "$t" >/dev/null 2>&1 || [ -x "$QUARTUS_BIN/../sopc_builder/bin/$t" ]; then log_line "  - found $t"; fi
  done
  # Questa - Altera/Intel FPGA Starter Edition (free, but needs a licence file).
  local vsim=""
  for d in "$QUARTUS_BIN/../../questa_fse/bin" "$QUARTUS_BIN/../../questa_fe/bin"; do [ -x "$d/vsim" ] && vsim="$d/vsim"; done
  command -v vsim >/dev/null 2>&1 && vsim="$(command -v vsim)"
  if [ -n "$vsim" ]; then
    c_ok "Questa found: $("$vsim" -version 2>&1 | head -1)"
    [ -z "${LM_LICENSE_FILE:-}${SALT_LICENSE_SERVER:-}" ] && \
      c_warn "Questa licence variable not set (LM_LICENSE_FILE or SALT_LICENSE_SERVER, depending on version)"
  else
    c_warn "Questa Starter not found (optional; the open-source simulators cover smoke tests)"
  fi
  if command -v jtagconfig >/dev/null 2>&1; then
    jtagconfig 2>&1 | log_block "jtagconfig (board connection; empty chain is OK if no board attached)"
    info "jtagconfig output logged. On Linux, USB-Blaster II needs udev rules (see report §12)."
  fi
}

smoke_sim() {
  local s
  for s in verilator icarus; do
    if (cd "$SMOKE/sim" && "$VENV/bin/python" run_smoke.py "$s") > "/tmp/chip2026_smoke_$s.log" 2>&1; then
      c_ok "cocotb smoke test on $s: $(grep '^SMOKE' "/tmp/chip2026_smoke_$s.log")"
    else
      c_fail "cocotb smoke test on $s failed (log below)"
      tail -30 "/tmp/chip2026_smoke_$s.log" | log_block "cocotb $s failure tail"
    fi
  done
}

smoke_formal() {
  local work; work="$(mktemp -d)"
  cp "$SMOKE/sim/smoke_counter.sv" "$SMOKE/sim/smoke_counter_props.sv" "$SMOKE/sim/smoke_formal.sby" "$work/"
  if (cd "$work" && sby -f smoke_formal.sby) > /tmp/chip2026_sby.log 2>&1; then
    c_ok "SymbiYosys smoke proof: $(grep -m1 -E 'summary: (successful|failed)' /tmp/chip2026_sby.log | sed 's/.*summary: //')"
  else
    c_fail "SymbiYosys smoke proof failed"; tail -20 /tmp/chip2026_sby.log | log_block "sby failure tail"
  fi
  rm -rf "$work"
}

smoke_lint() {
  if verilator --lint-only -Wall "$SMOKE/sim/smoke_counter.sv" >/tmp/chip2026_vlint.log 2>&1; then
    c_ok "verilator --lint-only -Wall clean on smoke DUT"
  else c_fail "verilator lint failed on smoke DUT"; fi
  if slang --quiet "$SMOKE/sim/smoke_counter.sv" >/tmp/chip2026_slang.log 2>&1; then
    c_ok "slang elaboration clean on smoke DUT"
  else c_fail "slang reported errors on smoke DUT"; fi
}

smoke_quartus() {
  [ "${SKIP_QUARTUS_SMOKE:-0}" = "1" ] && { c_warn "Quartus smoke compile skipped (SKIP_QUARTUS_SMOKE=1)"; return 0; }
  [ -z "${QUARTUS_BIN:-}" ] && return 0
  local work; work="$(mktemp -d)"
  cp "$SMOKE"/quartus/* "$work/"
  info "Running Quartus smoke compile for 5CSEBA6U23I7 (several minutes)..."
  if (cd "$work" && quartus_sh --flow compile smoke) > /tmp/chip2026_quartus.log 2>&1; then
    c_ok "Quartus compiled the smoke design for 5CSEBA6U23I7 (Cyclone V device support works)"
    # Raw report excerpts, verbatim. These also reveal the exact Cyclone V
    # resource-line labels needed by any report parser (e.g. weft-mcp).
    for f in "$work"/output_files/smoke.fit.summary "$work"/output_files/smoke.sta.summary; do
      [ -f "$f" ] && log_block "$(basename "$f") (verbatim)" < "$f"
    done
    [ -f "$work/output_files/smoke.flow.rpt" ] && \
      sed -n '/; Flow Summary/,/^$/p' "$work/output_files/smoke.flow.rpt" | log_block "Flow Summary (verbatim)"
    [ -f "$work/output_files/smoke.sof" ] && c_ok "Assembler produced smoke.sof (NOT for programming: no pin assignments)"
  else
    c_fail "Quartus smoke compile failed"; grep -iE "^Error|error \(" /tmp/chip2026_quartus.log | head -15 | log_block "Quartus errors"
  fi
  rm -rf "$work"
}

verify_claude() {
  if ! command -v claude >/dev/null 2>&1; then c_fail "Claude Code CLI not found"; return 1; fi
  c_ok "Claude Code: $(claude --version 2>&1 | head -1)"
  local list; list="$(cd "$REPO_ROOT" && claude plugin list 2>&1)"
  printf '%s\n' "$list" | log_block "claude plugin list (from repo root)"
  if printf '%s' "$list" | grep -A3 "$RAT_PLUGIN" | grep -qi "enabled"; then
    c_ok "Claude Code recognises $RAT_PLUGIN: $(printf '%s' "$list" | grep -A1 "$RAT_PLUGIN" | grep -m1 -i version | tr -s ' ')"
  else
    c_fail "$RAT_PLUGIN not listed as enabled for this project"
  fi
  printf '%s' "$list" | grep -q "gateflow@" && printf '%s' "$list" | grep -A3 "gateflow@" | grep -qi "enabled" && \
    c_warn "GateFlow is also enabled - overlapping agents; keep only one enabled"
}

verify_project_skills() {
  local sdir="$REPO_ROOT/.claude/skills" d name t py out n=0
  py="$VENV/bin/python"; [ -x "$py" ] || py="$(command -v python3)"
  if [ ! -d "$sdir" ]; then c_fail "no .claude/skills directory (project skills missing)"; return 1; fi
  for d in "$sdir"/*/; do
    [ -f "${d}SKILL.md" ] || continue
    name="$(basename "$d")"; n=$((n+1))
    if [ "$(head -1 "${d}SKILL.md")" = "---" ] && grep -q '^description:' "${d}SKILL.md"; then
      if "$py" - "${d}SKILL.md" <<'PYCHK' 2>/dev/null
import sys
fm = open(sys.argv[1], encoding="utf-8").read().split("---\n")[1]
try:
    import yaml
    yaml.safe_load(fm)
except ImportError:                       # no PyYAML: fall back to the known failure patterns
    for line in fm.splitlines():
        if line.startswith("description:"):
            v = line[len("description:"):].strip()
            if not (v[:1] in "\"'>|") and (": " in v or " #" in v):
                sys.exit(1)
PYCHK
      then c_ok "skill /$name: SKILL.md frontmatter is valid YAML with a description"
      else c_fail "skill /$name: frontmatter is not valid YAML (a plain description must not contain ': ' or ' #')"; fi
    else
      c_fail "skill /$name: SKILL.md lacks '---' frontmatter or 'description:'"
    fi
    for t in "${d}"scripts/*.py; do
      [ -f "$t" ] || continue
      if out="$("$py" "$t" --selftest 2>&1)"; then
        c_ok "skill /$name: $(printf '%s' "$out" | tail -1)"
      else
        c_fail "skill /$name: $(basename "$t") --selftest failed"
        printf '%s\n' "$out" | tail -10 | log_block "$name selftest failure"
      fi
    done
  done
  [ "$n" -gt 0 ] || c_fail "no project skills found in .claude/skills"
  if "$py" -c 'import json,sys; json.load(open(sys.argv[1]))' "$REPO_ROOT/.claude/settings.json" 2>/dev/null; then
    c_ok ".claude/settings.json is valid JSON"
  else
    c_fail ".claude/settings.json missing or not valid JSON"
  fi
}

verify_github() {
  command -v git >/dev/null 2>&1 || { c_fail "git not found"; return 1; }
  if ! git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    c_warn "not a git repository yet (run: scripts/setup_github.sh init)"; return 0
  fi
  local remote; remote="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || true)"
  if [ -n "$remote" ]; then c_ok "git remote origin: $remote"
  else c_warn "no git remote 'origin' yet (run: scripts/setup_github.sh init)"; fi
  if command -v gh >/dev/null 2>&1; then
    if gh auth status >/dev/null 2>&1; then c_ok "GitHub CLI (gh) is logged in"
    else c_warn "GitHub CLI installed but not logged in (run: gh auth login)"; fi
  else
    c_warn "GitHub CLI 'gh' not installed (Ubuntu: sudo apt install gh); plain git over HTTPS/SSH still works"
  fi
  if git -C "$REPO_ROOT" check-ignore -q .venv/pyvenv.cfg; then c_ok ".venv is git-ignored"
  else c_fail ".venv is NOT git-ignored (a commit would add ~70 MB)"; fi
}

header() {
  [ "$MODE" = "check" ] && return 0
  mkdir -p "$(dirname "$LOG")"
  [ -f "$LOG" ] || printf '# Tooling install & verification log\n\nAppend-only. Generated by `scripts/setup_tooling.sh`; every entry is raw tool output.\n' > "$LOG"
  printf '\n## %s run - %s - host %s (%s)\n\n' "$MODE" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(hostname)" "$(uname -srm)" >> "$LOG"
  [ -f /etc/os-release ] && log_line "- OS: $(. /etc/os-release; echo "$PRETTY_NAME")"
}

# --------------------------------------------------------------------------- main
case "$MODE" in
  check|install|verify) ;;
  *) echo "usage: $0 [check|install|verify]"; exit 2 ;;
esac
cd "$REPO_ROOT" || exit 1
header
load_env

if [ "$MODE" = "install" ]; then
  install_oss_cad_suite
  install_python_venv
  install_plugins
  write_env
  MODE=verify; header
fi

verify_versions
verify_quartus
if [ "$MODE" = "verify" ]; then
  smoke_lint
  smoke_sim
  smoke_formal
  smoke_quartus
  verify_claude
  verify_project_skills
  verify_github
else
  info "(check mode: smoke tests and Claude Code checks run only in 'verify')"
fi

printf '\nSummary: %d ok, %d warnings, %d failures\n' "$PASS" "$WARN" "$FAIL"
log_line ""; log_line "**Summary: $PASS ok, $WARN warnings, $FAIL failures**"
[ "$FAIL" -eq 0 ]
