#!/usr/bin/env bash
# scripts/test/phase8cd_verify.sh -- Phases 8c and 8d verification (evidence/phase08/8c/test_plan_8c.md V1-V8, 8d/test_plan_8d.md V1-V8), both simulators.
# Variants: 0 STORE and 1 STREAM (8c), 2 OVERLAP and 3 STRESS (8d, STRESS is test only). The 8b sampler is not changed by 8c/8d; its regression is scripts/test/phase8b_verify.sh (not rerun here).
# Usage: scripts/test/phase8cd_verify.sh
set -u
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
export KP_BUILD_DIR="${KP_BUILD_DIR:-$(mktemp -d -t chip2026_8cd_XXXX)}"
export KP_N="${KP_N:-3}"
export KP_CYCLES_OUT_DIR="${KP_CYCLES_OUT_DIR:-$KP_BUILD_DIR}"
overall=0
step() {
    local h=$1; shift
    echo "## $h"
    "$@" 2>&1 | grep -E "^\[(icarus|verilator)\]|passed|failed|^%Error|^%Warning|Build succeeded|errors|differences|reproduced|DIFFERS|OVERALL|ALL AS EXPECTED|UNEXPECTED|^\| |cocotb\.kpke_smp_top_s10 |cocotb\.regression .*(passed|failed)" | grep -v "^\s*$"
    local rc=${PIPESTATUS[0]}
    echo "rc=$rc"
    [ "$rc" -eq 0 ] || overall=1
}
FILES="rtl/keccak/keccak_pkg.sv rtl/keccak/keccak_round.sv rtl/keccak/keccak_f1600.sv rtl/keccak/keccak_sponge.sv rtl/keccak/keccak_f1600_r2.sv rtl/keccak/keccak_sponge_r2.sv rtl/sample/sample_ntt_core.sv rtl/sample/cbd2_core.sv rtl/sample/keccak_sampler.sv rtl/ntt/ntt_pkg.sv rtl/ntt/twiddle_rom.sv rtl/arith/twiddle_rom_half.sv rtl/ntt/pipe_delay.sv rtl/ntt/modmul_reduce_staged.sv rtl/arith/modmul_fold.sv rtl/arith/modmul_barrett.sv rtl/arith/modmul_montgomery.sv rtl/arith/modmul_sel.sv rtl/arith/half_mod.sv rtl/arith/butterfly_m6.sv rtl/mem/poly_mem_m10k.sv rtl/ntt/ntt_core_s10.sv rtl/ntt/ntt_core_s10_p5.sv rtl/sched/gamma_rom.sv rtl/sched/kpke_smp_prog_rom.sv rtl/sched/poly_store_smp.sv rtl/sched/pwm_unit.sv rtl/sched/kpke_sched_smp.sv rtl/sched/kpke_smp_top_s10.sv"
step "V2 golden model (STORE, STREAM, OVERLAP, STRESS) against the unmodified golden K-PKE, hazard checker" python3 -m pytest -q tb/golden/tests/test_kpke_smp_model.py
step "V2 ROM regenerated byte for byte" python3 scripts/build/gen_kpke_smp_roms.py --check
for cfg in "VAR=0 STREAM_A=0 OVERLAP=0 NPOLY=24" "VAR=1 STREAM_A=1 OVERLAP=0 NPOLY=12" "VAR=2 STREAM_A=1 OVERLAP=1 NPOLY=12" "VAR=3 STREAM_A=1 OVERLAP=1 NPOLY=12"; do
    G=""; for kv in $cfg; do G="$G -G$kv"; done
    step "V1 verilator --lint-only -Wall kpke_smp_top_s10 ($cfg)" verilator --lint-only -Wall $G $FILES --top-module kpke_smp_top_s10
    step "V1 slang kpke_smp_top_s10 ($cfg)" slang $(for kv in $cfg; do printf -- "-G %s " "$kv"; done) $FILES --top kpke_smp_top_s10
done
for var in 0 1 2 3; do
    for sim in verilator icarus; do
        step "V3-V6 $sim VAR=$var" env KP_VAR=$var python3 tb/smp/run_smp_tests.py "$sim"
    done
done
step "V7 formal 8c: formal/run/run_formal_phase8c.py" python3 formal/run/run_formal_phase8c.py
step "V7 formal 8d: formal/run/run_formal_phase8d.py" python3 formal/run/run_formal_phase8d.py
echo "## V8 Phase 6 files unmodified since their commit (git diff against the Phase 7 base 6874609)"
d=$(git diff --name-status 6874609 -- rtl/sched/kpke_sched.sv rtl/sched/kpke_sched_top.sv rtl/sched/kpke_sched_top_s10.sv rtl/sched/poly_store.sv rtl/sched/pwm_unit.sv rtl/sched/gamma_rom.sv rtl/sched/kpke_prog_rom.sv rtl/ntt rtl/arith rtl/mem | wc -l)
echo "modified Phase 6 / core files: $d"
[ "$d" = "0" ] || overall=1
[ "$overall" -eq 0 ] && echo "OVERALL: PASS" || echo "OVERALL: FAIL"
exit "$overall"
