`default_nettype none
`timescale 1ns/1ps
// formal/phase09-integration/9c/mlkem_core_formal_top.sv
// Phase 9c (evidence/phase09/9c/test_plan_9c.md, Amendment A2): control properties of the controller rtl/mlkem/mlkem_core.sv with the sub-blocks replaced by protocol stubs (stubs_9c.sv); the memories, the register file and the ROM are the real ones.
// Two copies of the core (A and B) run side by side. They get the same control inputs (op, start, host strobe and address, and the stubs' control signals f_c*, assumed equal) and DIFFERENT data (the host data, the stubs' data signals f_d*, the contents of the memories).
//   E1  non-interference: every control register of A equals that of B at all times, i.e. the sequence of states, the program counter, the counters and the strobes do not depend on any data (the proof of "no branch, address or count depends on a secret", for the controller)
//   S1  state and program counter in range
//   S2  busy_o is exactly "not idle"; done_o only when idle
//   S3  nothing writes a memory in the states LDP, HFD, SDL, RUN, CMP, FETCH, DISP: the host cannot write while busy
//   S4  the start strobes of the sub-blocks occur only in DISP, one at most, and only for their own micro-operation
//   S5  the engine host port is written only in LDP; the seed port only in SDL with a step below 8
//   S6  addresses generated by the controller itself (WR32, RD32, HGT, CMPK writes; HFD and RD32 reads) stay inside the memory they address
//   S7  step counters stay in range
// Control and range only; values are covered by simulation against the golden model. Free stub signals are `wire` (see stubs_9c.sv).

module mlkem_core_formal_top (
    input  wire         clk_i,
    input  wire         rst_ni,
    input  wire  [1:0]  op_i,
    input  wire         start_i,
    input  wire         h_we_i,
    input  wire  [11:0] h_addr_i,
    input  wire  [63:0] h_wdata_a_i,
    input  wire  [63:0] h_wdata_b_i,
    output wire         busy_a_o,
    output wire         done_a_o,
    output wire         busy_b_o,
    output wire         done_b_o,
    output wire  [63:0] h_rdata_a_o,
    output wire  [63:0] h_rdata_b_o
);

  // Phase 9M (test_plan_9m1.md): the load / store tasks sit in generate blocks of the core (CODEC_W2); -D W2 proves the core with the two-byte tasks (their stubs in formal/phase09m-optimisation/9m1/stubs_9m1.sv)
`ifdef W2
  `define LDP g_ld2.u_ld
  `define STP g_st2.u_st
  localparam bit FW2 = 1'b1;
`else
  `define LDP g_ld1.u_ld
  `define STP g_st1.u_st
  localparam bit FW2 = 1'b0;
`endif
  mlkem_core #(.CODEC_W2(FW2)) u_a (.clk_i(clk_i), .rst_ni(rst_ni), .op_i(op_i), .start_i(start_i), .busy_o(busy_a_o), .done_o(done_a_o), .h_we_i(h_we_i), .h_addr_i(h_addr_i), .h_wdata_i(h_wdata_a_i), .h_rdata_o(h_rdata_a_o));
  mlkem_core #(.CODEC_W2(FW2)) u_b (.clk_i(clk_i), .rst_ni(rst_ni), .op_i(op_i), .start_i(start_i), .busy_o(busy_b_o), .done_o(done_b_o), .h_we_i(h_we_i), .h_addr_i(h_addr_i), .h_wdata_i(h_wdata_b_i), .h_rdata_o(h_rdata_b_o));

`ifdef FORMAL
  logic f_init = 1'b1;
  always_ff @(posedge clk_i) f_init <= 1'b0;
  always_comb if (f_init) assume (!rst_ni);

  // the control signals of the stubs are the same in both copies; their data signals are free in each copy
  always_comb begin
    assume (u_a.u_eng.f_cfin == u_b.u_eng.f_cfin);
    assume (u_a.u_hash.f_cinr == u_b.u_hash.f_cinr);
    assume (u_a.u_hash.f_cov == u_b.u_hash.f_cov);
    assume (u_a.u_hash.f_ccl == u_b.u_hash.f_ccl);
    assume (u_a.u_hash.f_cfin == u_b.u_hash.f_cfin);
    assume (u_a.u_fo.f_cfin == u_b.u_fo.f_cfin);
    assume (u_a.`LDP.f_cfin == u_b.`LDP.f_cfin);
    assume (u_a.`LDP.f_creq == u_b.`LDP.f_creq);
    assume (u_a.`LDP.f_cwe == u_b.`LDP.f_cwe);
    assume (u_a.`LDP.f_cadr == u_b.`LDP.f_cadr);
    assume (u_a.`LDP.f_cslot == u_b.`LDP.f_cslot);
    assume (u_a.`LDP.f_ctadr == u_b.`LDP.f_ctadr);
    assume (u_a.`STP.f_cfin == u_b.`STP.f_cfin);
    assume (u_a.`STP.f_cwe == u_b.`STP.f_cwe);
    assume (u_a.`STP.f_cadr == u_b.`STP.f_cadr);
    assume (u_a.`STP.f_cslot == u_b.`STP.f_cslot);
    assume (u_a.`STP.f_ctadr == u_b.`STP.f_ctadr);
  end

  localparam logic [3:0] S_IDLE = 4'd0, S_FETCH = 4'd1, S_DISP = 4'd2, S_LDP = 4'd3, S_STP = 4'd4, S_HFD = 4'd5, S_HGT = 4'd6, S_SDL = 4'd7, S_RUN = 4'd8, S_WR32 = 4'd9, S_RD32 = 4'd10, S_CMP = 4'd11, S_CMPK = 4'd12;
  wire [3:0] sa = 4'(u_a.state_q);

  always_ff @(posedge clk_i) begin
    if (rst_ni) begin
      // E1: all control registers equal
      assert (u_a.state_q == u_b.state_q);
      assert (u_a.op_q == u_b.op_q);
      assert (u_a.pc_q == u_b.pc_q);
      if (sa != S_IDLE && sa != S_FETCH) assert (u_a.ins_q == u_b.ins_q);   // ins_q is loaded in FETCH (not reset): before that it is stale in both copies
      assert (u_a.done_q == u_b.done_q);
      assert (u_a.rd_rgn_q == u_b.rd_rgn_q);
      assert (u_a.fd_issued_q == u_b.fd_issued_q);
      assert (u_a.fd_cons_q == u_b.fd_cons_q);
      assert (u_a.fd_valid_q == u_b.fd_valid_q);
      assert (u_a.hold_v_q == u_b.hold_v_q);
      assert (u_a.hg_w_q == u_b.hg_w_q);
      assert (u_a.k_q == u_b.k_q);
      assert (u_a.cm_issued_q == u_b.cm_issued_q);
      assert (u_a.cm_valid_q == u_b.cm_valid_q);
      assert (busy_a_o == busy_b_o && done_a_o == done_b_o);
      // the control state of the stubs is equal too (supporting invariant: a stub's busy and done flags depend on control only)
      assert (u_a.u_eng.busy_q == u_b.u_eng.busy_q && u_a.u_eng.done_q == u_b.u_eng.done_q);
      assert (u_a.u_hash.busy_q == u_b.u_hash.busy_q && u_a.u_hash.done_q == u_b.u_hash.done_q);
      assert (u_a.u_fo.busy_q == u_b.u_fo.busy_q && u_a.u_fo.done_q == u_b.u_fo.done_q);
      assert (u_a.`LDP.busy_q == u_b.`LDP.busy_q && u_a.`LDP.done_q == u_b.`LDP.done_q);
      assert (u_a.`STP.busy_q == u_b.`STP.busy_q && u_a.`STP.done_q == u_b.`STP.done_q);
      assert (u_a.wr_en == u_b.wr_en && u_a.wr_rgn == u_b.wr_rgn && u_a.wr_addr == u_b.wr_addr && u_a.rd_addr == u_b.rd_addr);
      // S1
      assert (sa <= S_CMPK);
      assert (u_a.pc_q < 6'd32);
      // S2
      assert (busy_a_o == (sa != S_IDLE));
      if (done_a_o) assert (!busy_a_o);
      // S3
      if (sa == S_LDP || sa == S_HFD || sa == S_SDL || sa == S_RUN || sa == S_CMP || sa == S_FETCH || sa == S_DISP) assert (!u_a.wr_en);
      // S4
      assert (!(u_a.ld_start && u_a.st_start) && !(u_a.ld_start && u_a.hs_start) && !(u_a.ld_start && u_a.eng_start) && !(u_a.ld_start && u_a.fo_start));
      assert (!(u_a.st_start && u_a.hs_start) && !(u_a.st_start && u_a.eng_start) && !(u_a.st_start && u_a.fo_start));
      assert (!(u_a.hs_start && u_a.eng_start) && !(u_a.hs_start && u_a.fo_start) && !(u_a.eng_start && u_a.fo_start));
      if (u_a.ld_start || u_a.st_start || u_a.hs_start || u_a.eng_start || u_a.fo_start) assert (sa == S_DISP);
      if (u_a.ld_start) assert (u_a.opc == 4'd1);
      if (u_a.st_start) assert (u_a.opc == 4'd2);
      if (u_a.hs_start) assert (u_a.opc == 4'd3);
      if (u_a.eng_start) assert (u_a.opc == 4'd7);
      if (u_a.fo_start) assert (u_a.opc == 4'd10);
      // S5
      if (u_a.eng_tb_we) assert (sa == S_LDP);
      if (u_a.eng_seed_we) assert (sa == S_SDL && u_a.k_q < 4'd8);
      // supporting invariant: the stored micro-instruction is the ROM word of the current program counter (the program counter is stable while an operation runs)
      if (sa != S_IDLE && sa != S_FETCH) assert (u_a.ins_q == u_a.rom_w);
      // supporting invariants: the state of a running operation matches the opcode of the stored micro-instruction
      if (sa == S_LDP) assert (u_a.opc == 4'd1);
      if (sa == S_STP) assert (u_a.opc == 4'd2);
      if (sa == S_HFD) assert (u_a.opc == 4'd4);
      if (sa == S_HGT) assert (u_a.opc == 4'd5);
      if (sa == S_SDL) assert (u_a.opc == 4'd6);
      if (sa == S_RUN) assert (u_a.opc == 4'd7);
      if (sa == S_WR32) assert (u_a.opc == 4'd8);
      if (sa == S_RD32) assert (u_a.opc == 4'd9);
      if (sa == S_CMP || sa == S_CMPK) assert (u_a.opc == 4'd10);
      // S7
      if (sa == S_SDL) assert (u_a.k_q <= 4'd8);
      if (sa == S_WR32) assert (u_a.k_q <= 4'd4);
      if (sa == S_RD32) assert (u_a.k_q <= 4'd5);
      if (sa == S_CMPK) assert (u_a.k_q <= 4'd4);
      if (sa == S_HFD) begin
        assert (u_a.fd_issued_q <= u_a.f_hnw);
        assert (u_a.fd_issued_q == u_a.fd_cons_q + 9'(u_a.fd_valid_q) + 9'(u_a.hold_v_q));   // words requested = consumed + in flight + held
        assert (!(u_a.fd_valid_q && u_a.hold_v_q));
      end
      if (sa == S_CMP) assert (u_a.cm_issued_q <= 9'd136);
      // S6
      if (sa == S_WR32 && u_a.wr_en) assert (u_a.wr_rgn == 2'd0 && u_a.wr_addr < 9'd300);
      if (sa == S_RD32 && u_a.wr_en) assert (u_a.wr_rgn == 2'd3 && u_a.wr_addr < 9'd32);
      if (sa == S_HGT && u_a.wr_en) assert (u_a.wr_rgn == 2'd3 && u_a.wr_addr < 9'd32);
      if (sa == S_CMPK && u_a.wr_en) assert (u_a.wr_rgn == 2'd3 && u_a.wr_addr < 9'd32);
      if (sa == S_RD32 && u_a.k_q < 4'd4) assert (u_a.rd_addr < 9'd300);
      if (u_a.fd_issue) begin
        case (u_a.f_hsrc)
          3'd0: assert (u_a.rd_addr < 9'd300);
          3'd1, 3'd2: assert (u_a.rd_addr < 9'd136);
          3'd3: assert (u_a.rd_addr < 9'd32);
          default: ;
        endcase
      end
      if (u_a.cm_issue) assert (u_a.rd_addr < 9'd136);
      // reachability (anti-vacuity), cover mode only: KeyGen and Encaps can complete, a digest word can be written (depth 260)
      cover (done_a_o && u_a.op_q == 2'd0);
      cover (done_a_o && u_a.op_q == 2'd1);
      cover (sa == S_HGT && u_a.hg_take);
`ifdef DEEP
      // the longest program (Decaps, 30 micro-operations, two hashes of 136 to 148 words) needs more than 260 cycles even with stubs that finish at once (depth 480, define DEEP)
      cover (done_a_o && u_a.op_q == 2'd2);
      cover (sa == S_CMPK);
`endif
    end
  end
`endif

endmodule
`default_nettype wire
